# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  database: action_mailer_usage_dev
  pool: 5
  timeout: 5000
  username: root
  password: karan

